### PR TITLE
chore: update cpp-sc2 submodule release

### PR DESCRIPTION
**Pull request by ghost**
Updating pin for the cpp-sc2 submodule to utilize the improved CMake build configuration in BlankBot. Changes in cpp-sc2 are backwards compatible with current BlankBot build configuration, and has been tested with:
- Visual Studio 17 2022
- Visual Studio 16 2019
- Visual Studio 15 2017 Win64

### CODE REVIEW

**Review by alkurbatov — CHANGES_REQUESTED** [review]
Need to investigate CI failure.

**Comment by alkurbatov** [comment]
Also, I suggest to check compilation under the debug mode.
It fails now as libcivetweb has debug suffix.

**Comment by alkurbatov** [comment]
> Also, I suggest to check compilation under the debug mode.
> It fails now as libcivetweb has debug suffix.

This patch worked on OS X:
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index a4fd91b..b5bacc2 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -26,9 +26,7 @@ endif ()

 # Create the executable.
 add_executable(BlankBot ${BOT_SOURCES})
-target_link_libraries(BlankBot
-    sc2api sc2lib sc2utils sc2protocol civetweb libprotobuf
-)
+target_link_libraries(BlankBot cpp_sc2)

 if (MINGW)
     target_link_libraries(BlankBot ssp)
```

**Comment by ghost** [comment]
I have replicated the issue locally, was an error on my part but is ultimately part of what motivated [this change](https://github.com/cpp-sc2/cpp-sc2/pull/113/commits/7e071793b92caf56424f28d8c8d8dd4e10284533).

As for the error itself, it's with MSVC's default behavior with selecting the runtime library rather than the civetweb debug postfix:
```
...
Generating Code...
libprotobuf.lib(repeated_field.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Bot.obj [D:\a\blank-bot\blank-bot\build\src\BlankBot.vcxproj]
libprotobuf.lib(generated_message_util.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Bot.obj [D:\a\blank-bot\blank-bot\build\src\BlankBot.vcxproj]
libprotobuf.lib(int128.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in Bot.obj [D:\a\blank-bot\blank-bot\build\src\BlankBot.vcxproj]
...
```

`cpp-sc2` libraries are being compiled correctly using `set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")`, but MSVC is defaulting to the dynamic runtime for the `BlankBot` project. There are two paths:

1. `set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")` in the `BlankBot` project to match the subprojects
2. set `CMAKE_MSVC_RUNTIME` as an `ENV` variable or with `PARENT_SCOPE` in `cpp-sc2`. I really don't like this as the subproject is prescriptively configuring parent build directories. 

I have pushed the commit amending this configuration issue as per option 1. I wanted to keep the PR as atomic to the submodule update as possible, but this will have to do.

**Comment by alkurbatov** [comment]
Please pay attention to this one. It is still not resolved.

> Also, I suggest to check compilation under the debug mode.
> It fails now as libcivetweb has debug suffix.

**Comment by ghost** [comment]
> 

Another CMake gotcha... still learning I suppose.

`set_target_properties(civetweb-c-library PROPERTIES DEBUG_POSTFIX "d")` at the `cpp-sc2` level will not apply in the same way as the `civetweb-c-library` exports a different name from the library target. I preferred to minimize build config changes to `BlankBot` in the PR, but I will apply the `cpp_sc2` target for linking as you identified in your patch, and the issue will be resolved.

Although I will continue to look into the `OUTPUT_NAME` and `EXPORT_NAME` behavior as it applies to libraries and debug postfix/suffix behavior in CMake, as it is surprising CMake does not account for this (as far as I can tell).

**Review by alkurbatov — APPROVED** [review]
Thank you! Looks good to me.

**Pull request merged**
